train:
  seed: 1234
  learning_rate: 5.0e-05
  betas:
  - 0.9
  - 0.99
  total_steps: 150000
  max_to_keep: 5
data:
  data_columns:
  - mixture
  - vocals
  segment_size: 44100
model:
  type: bs_roformer
  stereo: true
  dim: 256
  depth: 12
  time_transformer_depth: 1
  freq_transformer_depth: 1
  multi_stft_resolutions_window_sizes:
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  stft_n_fft: 2048
  stft_win_length: 2048
  multi_stft_hop_size: 147
  use_shared_bias: false
  num_stems: 6
  instruments:
  - vocals
log:
  info_interval: 100
  eval_interval: 1000
  save_interval: 1000
  pth_dir: gs://[some google bucket path]/chkpt
  log_dir: logs
data_loader:
  dataset_path: '[need to be absolute path]/*.arrayrecord'
  host_number: 1
  global_batch_size: 8
  num_epochs: 100
  worker_count: 8
  drop_remainder: false
  shuffle: false
inference:
  batch_size: 8
  chunk_size: 352768
  num_overlap: 4
